name: Flask App CI

on:
  push:
    branches:
      - main

jobs:
  run-llm-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LLM.py script
        env:
          LLM: ${{ secrets.LLM }}
        run: python LLM.py

